services:
    database:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - database_data:/var/lib/postgresql/data:rw
        env_file:
            - .env
        ports:
            - "5432:5432"

volumes:
    database_data:
