imports:
    - { resource: ./services_dev.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Shared\Infrastructure\Bus\MessengerCommandBus: ~
    App\Shared\Infrastructure\Bus\MessengerQueryBus: ~
