services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    DataFixtures\:
        resource: '../tests/Fixtures'

    App\Shared\Infrastructure\Bus\MessengerCommandBus: ~
    App\Shared\Infrastructure\Bus\MessengerQueryBus: ~
