parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src'

    App\Products\Domain\Loan\LoanIssueService:
        arguments:
            $adjustments: !tagged 'products.loan.adjustment'

    _instanceof:
        App\Shared\Domain\Bus\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Shared\Domain\Bus\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        App\Products\Domain\Loan\Restriction\LoanRestriction:
            tags:
                - { name: products.loan.restriction }

        App\Products\Domain\Loan\Adjustment\LoanAdjustment:
            tags:
                - { name: products.loan.adjustment }